package com.neo.model;

import jakarta.persistence.*;
import lombok.Data;
import java.util.List;

@Data
@Entity
@Table(name = "category")
public class Category {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 50)
    private String name;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    private Category parent;

    @OneToMany(mappedBy = "parent", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("sort ASC")
    private List<Category> children;

    @Column(nullable = false)
    private Integer level;

    @Column(nullable = false)
    private Integer sort;

    @Column(nullable = false)
    private Boolean enabled;

    @Column(length = 200)
    private String description;

    // Getters and Setters (generated by Lombok)
}