package com.neo.model;

import jakarta.persistence.*;
import lombok.Data;
import java.util.List;

@Data
@Entity
@Table(name = "goods_tag")
public class GoodsTag {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 50)
    private String name;

    @Column(length = 200)
    private String description;

    @Column(nullable = false)
    private Boolean enabled;

    @ManyToMany(mappedBy = "tags")
    private List<Goods> goodsList;

    // Getters and Setters (generated by Lombok)
}