package com.neo.model;

import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name = "goods_category")
public class GoodsCategory {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    @Column(nullable = false, length = 50)
    private String name;

    @Column(length = 200)
    private String description;

    @Column(nullable = false)
    private Boolean enabled;

    @Column(nullable = false)
    private Integer sort;

    // Getters and Setters (generated by Lombok)
}