package com.neo.model;

import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;
import java.util.List;
import java.util.Date;

@Data
@Entity
@Table(name = "goods")
public class Goods {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 100)
    private String name;

    @Column(length = 500)
    private String description;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private GoodsCategory category;

    @ManyToMany
    @JoinTable(
        name = "goods_tag_relation",
        joinColumns = @JoinColumn(name = "goods_id"),
        inverseJoinColumns = @JoinColumn(name = "tag_id")
    )
    private List<GoodsTag> tags;

    @Column(nullable = false)
    private Integer stock;

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    @Column(precision = 10, scale = 2)
    private BigDecimal discountPrice;

    @Column(nullable = false)
    private Integer discountRate;

    @Column(length = 100)
    private String supplier;

    @Column(nullable = false)
    private Boolean isOnSale;

    @Column(nullable = false)
    private Date createTime;

    @Column(nullable = false)
    private Date updateTime;

    // Getters and Setters (generated by Lombok)
}