package com.neo.model;

import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name = "goods_attribute")
public class GoodsAttribute {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "goods_id", nullable = false)
    private Goods goods;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "attribute_id", nullable = false)
    private CategoryAttribute attribute;

    @Column(nullable = false, length = 100)
    private String value;

    // Getters and Setters (generated by Lombok)
}